### ISSUE TITLE
Explain what 'hold' means

### ISSUE THREAD

**Issue by Limess** [toplan/react-hold#1]
I just followed a link to this project and I don't understand what it does. This is because I don't understand the term
>hold

I think it would be valuable to add a definition of this to the head of the readme, and explain what this project does in terms of the definition.

**Comment by toplan** [comment]
I'm sorry I didn't make it clear. The `hold` in this library iscome from `placeholder`,  I am sure u know the function of placeholder in input tags. The `hold` means create a placeholder for components.

**Comment by toplan** [comment]
@Limess Hi, thanks for your remind, I am update the readme.
