### ISSUE TITLE
请问一下目前库币的微信和qq群如何加入？

### ISSUE THREAD

**Issue by yanyiwu** [toplan/react-hold#9]
rt

最早众筹的时候加入过，后来群太多删除了，现在想加入看看社区情况。感谢。

**Comment by toplan** [comment]
目前KuCoin只针对国外用户运营，可以关注reddit，推特，以及telegram。更详细的可以查看官网底部的链接。

**Comment by yanyiwu** [comment]
好的，谢谢回复，最早参加众筹得时候有个群，但是不知道后来哪去了，找不到了。如果确实没有的话就算了，

**Comment by toplan** [comment]
谢谢支持，微信群和QQ群，去年就解散了，目前没有官方的群了。
